env: 
  global: 
    - secure: bOPhFqXlBfwm73ac6BMSba2UR3vwnYVDqyXeAs/5SxrW2hW7/V/MmYLQL3h3BpOYfPBa1ganEAKYrd9K6HWJN16MHyROBEbFpZmZ5DFbK/pUjYaJp+8giSytxWBzEjo2f129azETNgvzjANbpAe0+uYaxupUPvpfQkPPrII+2Jc=

os: linux


dist: trusty
language: generic

matrix:
  include: 
#    - env: recipe=ipopt_mingwoct_trusty compilerprefix=i686-w64-mingw32 BITNESS=32
#    - env: recipe=ipopt_mingw_trusty compilerprefix=x86_64-w64-mingw32 BITNESS=64
#    - env: recipe=ipopt_mingw_trusty compilerprefix=i686-w64-mingw32 BITNESS=32
#    - env: recipe=ipopt_trusty
#    - env: recipe=ipopt_trusty GCCVERSION=4.6
#     - os: osx
#       env: recipe=ipopt_osx GCCVERSION=4.9
 
#    - env: recipe=bonmin_mingwoct_trusty compilerprefix=i686-w64-mingw32 BITNESS=32   
#    - env: recipe=bonmin_mingw_trusty compilerprefix=x86_64-w64-mingw32 BITNESS=64
#    - env: recipe=bonmin_mingw_trusty compilerprefix=i686-w64-mingw32 BITNESS=32
#    - env: recipe=bonmin_trusty
#    - env: recipe=bonmin_trusty GCCVERSION=4.6
#     - {env: recipe=bonmin_osx GCCVERSION=4.9, os: osx}
 
#    - env: recipe=ecos_mingw_trusty compilerprefix=x86_64-w64-mingw32 BITNESS=64
#    - env: recipe=ecos_mingw_trusty compilerprefix=i686-w64-mingw32 BITNESS=32
#    - env: recipe=ecos_trusty
#    - env: recipe=ecos_trusty GCCVERSION=4.6
#     - os: osx
#       env: recipe=ecos_osx GCCVERSION=4.9

#    - env: recipe=lapack_mingwoct_trusty compilerprefix=i686-w64-mingw32 BITNESS=32
#    - env: recipe=lapack_mingw_trusty compilerprefix=x86_64-w64-mingw32 BITNESS=64
#    - env: recipe=lapack_mingw_trusty compilerprefix=i686-w64-mingw32 BITNESS=32
  
     - env: recipe=slicot_mingw_trusty compilerprefix=x86_64-w64-mingw32 BITNESS=64
     - env: recipe=slicot_mingw_trusty compilerprefix=i686-w64-mingw32 BITNESS=32
  
#    - env: recipe=clang_mingwoct_trusty compilerprefix=i686-w64-mingw32 BITNESS=32
#    - env: recipe=clang_mingw_trusty compilerprefix=x86_64-w64-mingw32 BITNESS=64
#    - env: recipe=clang_mingw_trusty compilerprefix=i686-w64-mingw32 BITNESS=32
#    - env: recipe=clang_trusty
#    - env: recipe=clang_trusty GCCVERSION=4.6
#     - os: osx
#       env: recipe=clang_osx GCCVERSION=4.9
      
#    - env: recipe=swig_trusty
#    - env: recipe=swig_matlab_trusty BAKEVERSION=matlab-customdoc
#    - env: recipe=swig_matlab_trusty BAKEVERSION=b921b0ee5fa928a16
#    - env: recipe=swig_matlab_trusty BAKEVERSION=82714bf35c33fe2
#    - env: recipe=swig_matlab_trusty BAKEVERSION=234d6ea3a08ef71
    
#     - { os: osx, env: recipe=swig_matlab_osx BAKEVERSION=matlab-customdoc}
#     - { os: osx, env: recipe=swig_matlab_osx BAKEVERSION=b921b0ee5fa928a16}
#     - { os: osx, env: recipe=swig_matlab_osx BAKEVERSION=82714bf35c33fe2}
#     - { os: osx, env: recipe=swig_matlab_osx BAKEVERSION=234d6ea3a08ef71}
#    - env: recipe=mingw_octave_trusty

#    - env: recipe=hsl_mingwoct_trusty compilerprefix=i686-w64-mingw32 BITNESS=32
#    - env: recipe=hsl_mingw_trusty compilerprefix=i686-w64-mingw32 BITNESS=32
#    - env: recipe=hsl_mingw_trusty compilerprefix=x86_64-w64-mingw32 BITNESS=64
    
#    - env: recipe=hsl_trusty
#    - env: recipe=hsl_trusty GCCVERSION=4.6
#     - { env: recipe=hsl_osx, os: osx, GCCVERSION=4.9 }
    
    
python:
- "2.7_with_system_site_packages"
before_install:
  - |
    if [[ $TRAVIS_OS_NAME == *linux* ]]
    then
      sudo dpkg --add-architecture i386
      sudo apt-get update -q
      sudo apt-get install libpython2.7-dev libc6:i386 libncurses5:i386 libstdc++6:i386
      sudo apt-get update -qq
      if [[ $GCCVERSION == 4.6 ]]
        then
          sudo apt-get install -y gcc-4.6 g++-4.6 gfortran-4.6
          export CC=gcc-4.6
          export CXX=g++-4.6
          export FC=gfortran-4.6
          export F77=gfortran-4.6
        else
          sudo apt-get install -y gcc g++ gfortran    
      fi
    else
      shell_session_update() { :; } # Workaround for travis-ci/travis-ci#6522
      brew reinstall gcc49 --with-fortran
      export FC=gfortran-4.9
      export F77=gfortran-4.9
      sudo install_name_tool -id "@rpath/libgfortran.3.dylib" /usr/local/lib/gcc/4.9/libgfortran.3.dylib
      sudo install_name_tool -id "@rpath/libquadmath.0.dylib" /usr/local/lib/gcc/4.9/libquadmath.0.dylib
      sudo install_name_tool -id "@rpath/libgcc_s.1.dylib" /usr/local/lib/gcc/4.9/libgcc_s.1.dylib
      sudo install_name_tool -id "@rpath/libgomp.1.dylib" /usr/local/lib/gcc/4.9/libgomp.1.dylib
      export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/lib/gcc/4.9/
    fi
  - source recipes/setup.sh
install:
  - set -e
  - source shellhelpers && false || allowfail 1 && echo "okay"
  - source recipes/$recipe.sh
script:
  - echo "All is fine"
  
