env: 
  global: 
    - secure: bOPhFqXlBfwm73ac6BMSba2UR3vwnYVDqyXeAs/5SxrW2hW7/V/MmYLQL3h3BpOYfPBa1ganEAKYrd9K6HWJN16MHyROBEbFpZmZ5DFbK/pUjYaJp+8giSytxWBzEjo2f129azETNgvzjANbpAe0+uYaxupUPvpfQkPPrII+2Jc=
  matrix:
    - recipe=coinhsl
    - recipe=snopt7
python:
- "2.7_with_system_site_packages"
compiler: 
  - gcc
before_install:
  - sudo apt-get update -q
  - sudo apt-get dist-upgrade
  - sudo apt-get install ia32-libs -y
  - pwd 
  - recipes/setup.sh
  - ls
  - ls restricted
  - file restricted/GetMac.linux32.new
  - restricted/GetMac.linux32.old
  - ls
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc g++ gfortran
install: 
  - recipes/$recipe.sh
script:
  - echo "All is fine"
  
