env: 
  global: 
    - secure: bOPhFqXlBfwm73ac6BMSba2UR3vwnYVDqyXeAs/5SxrW2hW7/V/MmYLQL3h3BpOYfPBa1ganEAKYrd9K6HWJN16MHyROBEbFpZmZ5DFbK/pUjYaJp+8giSytxWBzEjo2f129azETNgvzjANbpAe0+uYaxupUPvpfQkPPrII+2Jc=

os: linux
dist: trusty
language: generic

matrix:
  include:
#     - os: osx
#       before_install:
#         - recipes/setup.sh
#       env: recipe=ipopt_osx
#     - os: osx
#       before_install:
#         - recipes/setup.sh
#       env: recipe=clang_osx
#    - os: osx
#      before_install:
#        - recipes/setup.sh
#      env: recipe=ecos_osx
#     - os: osx
#       before_install:
#        - recipes/setup.sh
#      env: recipe=swig_matlab_fixed_osx
#    - env: recipe=ipopt
#    - env: recipe=snopt75
#    - env: recipe=coinhsl
#     - env: recipe=mingw64_coinhsl
#     - env: recipe=mingw_coinhsl
#    - env: recipe=snopt7
#    - env: recipe=swig
#     - env: recipe=swig_matlab
#     - env: recipe=swig_matlab_fixed
#    - env: recipe=ipopt
#     - env: recipe=mingw_ipopt
     - env: recipe=mingw64_ipopt_trusty
#    - env: recipe=mingw_lapack
#    - env: recipe=mingw64_lapack
#     - env: recipe=mingw64_clang
#     - env: recipe=mingw_clang
#     - env: recipe=clang
#    - env: recipe=mingw64_ecos
#    - env: recipe=mingw_ecos
#    - env: recipe=ecos
#    - env: recipe=gcc47

python:
- "2.7_with_system_site_packages"
compiler: 
  - gcc
before_install:
  - sudo apt-get update -q
  - sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386
  - recipes/setup.sh
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc g++ gfortran
install: 
  - recipes/$recipe.sh
  - source shellhelpers && false || allowfail 1 && echo "okay"
script:
  - echo "All is fine"
  
