env: 
  global: 
  - IPOPT_DEFAULT_LINEAR_SOLVER=ma57
  - LD_LIBRARY_PATH=/home/travis/casadi/casadi/coinhsl-install/lib
  - secure: bOPhFqXlBfwm73ac6BMSba2UR3vwnYVDqyXeAs/5SxrW2hW7/V/MmYLQL3h3BpOYfPBa1ganEAKYrd9K6HWJN16MHyROBEbFpZmZ5DFbK/pUjYaJp+8giSytxWBzEjo2f129azETNgvzjANbpAe0+uYaxupUPvpfQkPPrII+2Jc=
compiler: 
  - gcc
before_install:
  - pwd 
  - recipes/setup.sh
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc g++ gfortran
install: 
  - recipes/coinhsl.sh
