env: 
  global: 
    - secure: bOPhFqXlBfwm73ac6BMSba2UR3vwnYVDqyXeAs/5SxrW2hW7/V/MmYLQL3h3BpOYfPBa1ganEAKYrd9K6HWJN16MHyROBEbFpZmZ5DFbK/pUjYaJp+8giSytxWBzEjo2f129azETNgvzjANbpAe0+uYaxupUPvpfQkPPrII+2Jc=

os: linux

dist: trusty
language: generic

matrix:
  include: 
#    - env: recipe=ipopt_mingw_trusty compilerprefix=x86_64-w64-mingw32 BITNESS=64
#    - env: recipe=ipopt_mingw_trusty compilerprefix=i686-w64-mingw32 BITNESS=32
#    - env: recipe=ipopt_trusty
#    - os: osx
#      env: recipe=ipopt_osx
    
#    - env: recipe=bonmin_mingw_trusty compilerprefix=x86_64-w64-mingw32 BITNESS=64
#    - env: recipe=bonmin_mingw_trusty compilerprefix=i686-w64-mingw32 BITNESS=32
#    - env: recipe=bonmin_trusty
    - {env: recipe=bonmin_osx, os: osx}
 
#    - env: recipe=ecos_mingw_trusty compilerprefix=x86_64-w64-mingw32 BITNESS=64
#    - env: recipe=ecos_mingw_trusty compilerprefix=i686-w64-mingw32 BITNESS=32
#    - env: recipe=ecos_trusty
#    - os: osx
#      env: recipe=ecos_osx

#    - env: recipe=lapack_mingw_trusty compilerprefix=x86_64-w64-mingw32 BITNESS=64
#    - env: recipe=lapack_mingw_trusty compilerprefix=i686-w64-mingw32 BITNESS=32
    
#    - env: recipe=clang_mingw_trusty compilerprefix=x86_64-w64-mingw32 BITNESS=64
#    - env: recipe=clang_mingw_trusty compilerprefix=i686-w64-mingw32 BITNESS=32
#    - env: recipe=clang_trusty
#    - os: osx
#      env: recipe=clang_osx
      
#    - env: recipe=swig_trusty
#    - env: recipe=swig_matlab
#    - os: osx
#      env: recipe=swig_matlab_osx

#    - env: recipe=hsl_trusty
#    - env: recipe=hsl_osx
    
    
python:
- "2.7_with_system_site_packages"
compiler: 
  - gcc
before_install:
  - |
    if [[ $TRAVIS_OS_NAME == *linux* ]]
    then
    sudo dpkg --add-architecture i386
    sudo apt-get update -q
    sudo apt-get install libpython2.7-dev libc6:i386 libncurses5:i386 libstdc++6:i386
    sudo apt-get update -qq
    sudo apt-get install -y gcc g++ gfortran
    fi
  - source recipes/setup.sh
install:
  - set -e
  - source shellhelpers && false || allowfail 1 && echo "okay"
  - source recipes/$recipe.sh
script:
  - echo "All is fine"
  
